name: Publish

on:
  workflow_run:
    workflows: CI
    branches: master
    types: completed

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/')}}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo package
      - run: cargo publish --token ${{ secrets.CARGO_PUBLISH_TOKEN }}
